import worli from "@/assets/hero-worli.jpg";
import bandra from "@/assets/hero-bandra.jpg";
import malabar from "@/assets/hero-malabar.jpg";
import tower from "@/assets/property-tower.jpg";

export type Property = {
  slug: string; name: string; location: string; neighborhood: string; image: string;
  gallery: string[]; price: string; priceValue: number; bhk: string; area: string;
  type: string; availability: string; possession: string; status: string;
  amenities: string[]; description: string; featured?: boolean; added: string;
};

export const properties: Property[] = [
  { slug:"the-reserve-worli", name:"The Reserve", location:"Worli Sea Face, Mumbai", neighborhood:"Worli", image:worli, gallery:[worli,tower,malabar,bandra], price:"₹ 12.8 Cr", priceValue:12.8, bhk:"4 BHK", area:"3,180 sq.ft.", type:"Apartment", availability:"Ready", possession:"Immediate", status:"Available", amenities:["Sea-facing lounge","Private lift","Pool deck","Concierge","Fitness studio","Residents’ salon"], description:"A serene sea-facing residence composed around light, proportion and uninterrupted western views. The private arrival, expansive living room and quietly detailed material palette create an elegant home above Mumbai’s most coveted shoreline.", featured:true, added:"2026-09-18" },
  { slug:"casa-verde-bandra", name:"Casa Verde", location:"Pali Hill, Bandra West", neighborhood:"Bandra", image:bandra, gallery:[bandra,worli,tower,malabar], price:"₹ 8.6 Cr", priceValue:8.6, bhk:"3 BHK", area:"2,240 sq.ft.", type:"Penthouse", availability:"Ready", possession:"Immediate", status:"Available", amenities:["Private terrace","Club lounge","Gymnasium","Valet parking","Garden court","Security"], description:"An intimate Pali Hill address where generous indoor spaces open to a planted terrace. Warm natural materials, framed city views and a sense of privacy define this considered urban home.", featured:true, added:"2026-09-15" },
  { slug:"malabar-house", name:"Malabar House", location:"Walkeshwar, South Mumbai", neighborhood:"South Mumbai", image:malabar, gallery:[malabar,worli,bandra,tower], price:"₹ 18.4 Cr", priceValue:18.4, bhk:"4 BHK", area:"3,650 sq.ft.", type:"Apartment", availability:"Ready", possession:"Immediate", status:"Available", amenities:["Harbour views","Library lounge","Private lobby","Spa suite","Housekeeping","Four-car parking"], description:"A rare high-floor home overlooking the harbour, designed for gracious entertaining and quiet retreat. Calm stone, dark timber and carefully framed views lend the residence its timeless character.", featured:true, added:"2026-09-10" },
  { slug:"the-courtyard-juhu", name:"The Courtyard", location:"Juhu Tara Road, Mumbai", neighborhood:"Juhu", image:tower, gallery:[tower,bandra,worli,malabar], price:"₹ 7.9 Cr", priceValue:7.9, bhk:"3 BHK", area:"2,080 sq.ft.", type:"Apartment", availability:"Under construction", possession:"December 2027", status:"Available", amenities:["Arrival court","Lap pool","Screening room","Gymnasium","Children’s room","Guest suites"], description:"A limited collection of residences around a landscaped central court, minutes from the sea. Deep balconies, thoughtful planning and a warm architectural language make everyday living feel composed.", added:"2026-09-20" },
  { slug:"atelier-lower-parel", name:"Atelier 51", location:"Lower Parel, Mumbai", neighborhood:"Lower Parel", image:worli, gallery:[worli,malabar,tower,bandra], price:"₹ 6.2 Cr", priceValue:6.2, bhk:"3 BHK", area:"1,860 sq.ft.", type:"Apartment", availability:"Ready", possession:"Immediate", status:"Available", amenities:["Business lounge","Pool terrace","Fitness studio","Concierge","Pet garden","EV charging"], description:"A refined city residence with open skyline views and carefully resolved interiors, exceptionally connected to Mumbai’s commercial and cultural districts.", added:"2026-09-19" },
  { slug:"lakehouse-powai", name:"Lakehouse", location:"Powai, Mumbai", neighborhood:"Powai", image:bandra, gallery:[bandra,tower,malabar,worli], price:"₹ 4.4 Cr", priceValue:4.4, bhk:"3 BHK", area:"1,720 sq.ft.", type:"Apartment", availability:"Under construction", possession:"June 2028", status:"Available", amenities:["Lake promenade","Clubhouse","Tennis court","Pool","Co-working lounge","Gardens"], description:"Contemporary lake-edge living with long green views, generous community spaces and a calm, family-focused atmosphere.", added:"2026-09-17" },
  { slug:"altamount-residences", name:"Altamount Residences", location:"Altamount Road, Mumbai", neighborhood:"South Mumbai", image:malabar, gallery:[malabar,tower,worli,bandra], price:"₹ 24.5 Cr", priceValue:24.5, bhk:"5 BHK", area:"4,800 sq.ft.", type:"Duplex", availability:"Ready", possession:"Immediate", status:"By appointment", amenities:["Private pool","Wine room","Spa","Concierge","Private dining","Six-car parking"], description:"A singular duplex residence created for exceptional scale, discretion and service at one of Mumbai’s most distinguished addresses.", added:"2026-09-12" },
  { slug:"harbour-line-colaba", name:"Harbour Line", location:"Colaba, Mumbai", neighborhood:"South Mumbai", image:tower, gallery:[tower,malabar,bandra,worli], price:"₹ 10.2 Cr", priceValue:10.2, bhk:"3 BHK", area:"2,410 sq.ft.", type:"Apartment", availability:"Ready", possession:"Immediate", status:"Available", amenities:["Harbour terrace","Library","Concierge","Gymnasium","Guest suite","Valet parking"], description:"A composed harbour-side home combining historic South Mumbai context with the comfort and privacy of a contemporary residence.", added:"2026-09-11" },
];
export const getProperty=(slug:string)=>properties.find(p=>p.slug===slug);
